#! /bin/sh

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

if [[ "$instance" = "gimp"* ]] ; then
	    case "$role" in
		gimp-action-search-dialog)
		echo "state=floating border=off"
		;;
	    esac
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gimp desktop=^8 follow=on 
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
